// Copyright (c) 2019-2023 ReactiveUI Association Incorporated. All rights reserved.
// ReactiveUI Association Incorporated licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Minimalist.Reactive.SystemReactiveBridge.Generator;

/// <summary>
/// Emits opt-in System.Reactive-shaped bridge extensions when System.Reactive symbols are visible to the consumer compilation.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SystemReactiveBridgeGenerator : IIncrementalGenerator
{
    private const string MarkerSource = """
// <auto-generated />
namespace Minimalist.Reactive.SystemReactiveBridge.Generated;

[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
internal sealed class MinimalistSystemReactiveBridgeGeneratedAttribute : global::System.Attribute
{
    public MinimalistSystemReactiveBridgeGeneratedAttribute(string generatorVersion) => GeneratorVersion = generatorVersion;

    public string GeneratorVersion { get; }
}
""";

    private const string BridgeSource = """
// <auto-generated />
#nullable enable
namespace Minimalist.Reactive.SystemReactiveBridge;

/// <summary>
/// Adapter methods emitted only for compilations that already reference System.Reactive.
/// </summary>
internal static class SystemReactiveSignalBridge
{
    /// <summary>
    /// Treats any System.Reactive/BCL observable as a Minimalist signal source.
    /// </summary>
    public static global::System.IObservable<T> AsMinimalistSignal<T>(this global::System.IObservable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return source;
    }

    /// <summary>
    /// Exposes a Minimalist signal as a System.Reactive-compatible observable without adding a production dependency.
    /// </summary>
    public static global::System.IObservable<T> AsSystemObservable<T>(this global::System.IObservable<T> source)
    {
        if (source == null)
        {
            throw new global::System.ArgumentNullException(nameof(source));
        }

        return source;
    }
}
""";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "MinimalistSystemReactiveBridgeGeneratedAttribute.g.cs",
                SourceText.From(MarkerSource, Encoding.UTF8)));

        context.RegisterSourceOutput(context.CompilationProvider, static (output, compilation) =>
        {
            if (compilation.GetTypeByMetadataName("System.Reactive.Linq.Observable") != null)
            {
                output.AddSource("SystemReactiveSignalBridge.g.cs", SourceText.From(BridgeSource, Encoding.UTF8));
            }
        });
    }
}
