name: BuildOnly

on:
  push:
    branches-ignore:
      - main

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET (With cache)
        uses: actions/setup-dotnet@v5.2.0
        with:
         dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
         dotnet-quality: 'preview'
         cache: true
         cache-dependency-path: |
           **/Directory.Packages.props
           **/*.sln
           **/*.csproj
           **/global.json
           **/nuget.config

      - name: NBGV
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
      - run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          vs-prerelease: true

      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v5
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: Restore'
        run: dotnet restore ./src/Minimalist.Reactive.sln

      - name: 'Run: Build'
        run: dotnet build ./src/Minimalist.Reactive.sln --configuration Release --no-restore --verbosity minimal

      
      - name: Tests + Coverage (MTP)
        shell: pwsh
        run: |
          dotnet test `
            --project ./src/Minimalist.Reactive.Tests/Minimalist.Reactive.Tests.csproj `
            --configuration Release `
            --no-build `
            --coverage `
            --coverage-output-format cobertura `
            --results-directory ./TestResults `
            -- --minimum-expected-tests 1

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: tmp-coverage
          path: |
            ./**/TestResults/**/*.cobertura.xml
          if-no-files-found: warn
          retention-days: 3
